---
title: CURI Banks Provisional Data Visualization
author: Henry Fisher
output: 
  pdf_document:
    fig_height: 3.5
    fig_width: 7
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
library(tidyverse)
```


```{r, include = FALSE}
banks1 <- read_csv("~/CURI 2023/CURI_sim_13.1.csv")
banks2 <- read_csv("~/CURI 2023/CURI_sim_13.2.csv")
banks3 <- read_csv("~/CURI 2023/CURI_sim_13.3.csv")
banks4 <- read_csv("~/CURI 2023/CURI_sim_13.4.csv")
degree_distribution <- read_csv("~/CURI 2023/CURI_sim_10_degree_distribution.csv")
```

```{r}
banks <- rbind(banks1, banks2, banks3, banks4)
```

```{r}
banks %>%
  ggplot(aes(x = `Number of links`)) +
    geom_density(alpha = 0.75, fill = "lightskyblue1") +
    theme_linedraw() +
    theme(axis.text.y = element_blank(),
          axis.ticks = element_blank()) +
    xlab("# of Edges Distribution")
```

```{r}
banks %>%
  rename(original = old_shortfall_dollars,
         `added link` = new_shortfall_dollars) %>%
  select(`Generated Graph`, `original`, `added link`) %>%
  pivot_longer(cols = 2:3, values_to = "shortfall") %>%
  ggplot(aes(y = shortfall, x = fct_reorder(name, shortfall), fill = name)) +
    geom_violin() +
    geom_boxplot(width = 0.5) +
    scale_fill_brewer() +
    theme_linedraw() +
    #theme(axis.text.y = element_blank(), axis.ticks = element_blank()) +
    xlab("Total Money not Repaid (in millions of dollars)")
```

```{r}
points <- banks %>%
  rename(old = old_shortfall_dollars, new = new_shortfall_dollars) %>%
  select(`Generated Graph`, `old`, `new`) %>%
  mutate(delta = new - old,
         y = 0)

shortfall_diff <- banks %>%
  rename(old = old_shortfall_dollars, new = new_shortfall_dollars) %>%
  select(`Generated Graph`, `old`, `new`) %>%
  mutate(delta = new - old)
ggplot(data = shortfall_diff, aes(x = delta)) +
  #geom_histogram(alpha = 0.8, fill = "black", bins = 1000) +
  geom_density(alpha = 0.90, fill = "lightskyblue1") +
  geom_point(data = points, aes(x = delta, y = y), alpha = 0.3, size = 0.8) +
    scale_fill_brewer() +
    theme_linedraw() +
    theme(axis.text.y = element_blank(),
          axis.ticks = element_blank(),
          #panel.grid.major = element_blank()
          panel.grid.minor = element_blank()
          ) +
    ggtitle("") +
    coord_cartesian(ylim = c(0, 0.005)) +
    ylab("Density") +
    xlab("Dollar Change in Millions")
```

```{r}
banks %>%
  rename(old = old_shortfall_dollars, new = new_shortfall_dollars) %>%
  select(`Generated Graph`, `old`, `new`) %>%
  mutate(delta = new - old) %>%
  ggplot(aes(x = delta)) +
    geom_histogram(fill = "lightskyblue1", bins = 100) +
    geom_point(data = points, aes(x = delta, y = y), alpha = 0.3, size = 0.8) +
    theme_linedraw() +
    theme(axis.text.x = element_blank(),
          axis.ticks = element_blank()) +
    ggtitle("Shortfall Difference from Added Link") +
    ylab("Density") +
    xlab("Dollar Change in Millions")
```

```{r}
banks %>%
  rename(old = old_shortfall_dollars, new = new_shortfall_dollars) %>%
  select(`Generated Graph`, `old`, `new`) %>%
  mutate(delta = abs(new - old)) %>%
  ggplot(aes(x = delta)) +
    geom_density(fill = "lightskyblue1") +
    geom_point(data = points, aes(x = abs(delta), y = y), alpha = 0.5) +
    theme_linedraw() +
    theme(axis.text.y = element_blank(), axis.ticks = element_blank()) +
    ggtitle("Absolute Shortfall Difference from Added Link") +
    ylab("Density") +
    xlab("Dollar Change in Millions")
```

```{r}
banks %>%
  select(`Generated Graph`, old_delinquent_count, 
         new_delinquent_count) %>%
  rename(`original` = old_delinquent_count, 
         `added link` = new_delinquent_count) %>%
  pivot_longer(cols = 2:3, values_to = "count") %>%
  ggplot(aes(y = count, x = fct_reorder(name, -count), fill = name)) +
    geom_violin() +
    geom_boxplot(width = 0.5) +
    scale_fill_brewer() +
    theme_linedraw() +
    #theme(axis.text.y = element_blank(), axis.ticks = element_blank()) +
    xlab("Number of Banks with Shortfall")
```

```{r}
banks %>%
  select(`Generated Graph`, old_delinquent_count, 
         new_delinquent_count) %>%
  rename(`original count` = old_delinquent_count, 
         `new count` = new_delinquent_count) %>%
  mutate(delta = `new count` - `original count`) %>%
  ggplot(aes(x = abs(delta))) +
    geom_bar(alpha = 0.85, fill = "lightskyblue1") +
    theme_linedraw() +
    xlab("change in # of delinquent banks added link")
```

```{r}
banks %>%
  mutate(delta = abs(new_minus_old_shortfall_dollars)) %>%
  summarize(`minimum` = min(delta),
            `median` = median(delta),
            `mean` = mean(delta),
            `maximum` = max(delta)) %>%
  pivot_longer(cols = 1:4, names_to = "measure") %>%
  ggplot(aes(x = fct_reorder(measure, value), y = value)) +
    geom_col(fill = "lightskyblue1", alpha = 0.85) +
    theme_linedraw() +
    xlab("Effect of system shortfall from added link (millions of dollars)")
```

```{r}
banks %>%
  select(`Generated Graph`, new_loaner_ID, new_borrower_ID) %>%
  rename(loaner = new_loaner_ID, borrower = new_borrower_ID) %>%
  pivot_longer(cols = 2:3, values_to = "bank") %>%
  ggplot(aes(y = bank, x = name, fill = name)) +
    geom_violin() +
    geom_boxplot(width = 0.4) +
    scale_fill_brewer() +
    theme_linedraw() +
    theme(axis.text.y = element_blank(), axis.ticks = element_blank()) +
    xlab("Distribution of added link with while-loop (100 bank network)")
```

```{r}
banks %>%
  select(`Generated Graph`, old_shortfall_loan_count, 
         new_shortfall_loan_count) %>%
  rename(`original` = old_shortfall_loan_count, 
         `added link` = new_shortfall_loan_count) %>%
  pivot_longer(cols = 2:3, values_to = "count") %>%
  ggplot(aes(y = count, x = fct_reorder(name, count), fill = name)) +
    geom_violin() +
    geom_boxplot(width = 0.3) +
    scale_fill_brewer() +
    theme_linedraw() +
    ggtitle("Number of Loans with Shortfall") +
    xlab("Network")
```

```{r}
t.test(banks$old_shortfall_dollars, banks$new_shortfall_dollars, paired = TRUE)
```

```{r}
t.test(banks$old_delinquent_count, banks$new_delinquent_count, paired = TRUE)
```

```{r}
t.test(banks$old_shortfall_bank_count, banks$new_shortfall_bank_count, paired = TRUE)
```

```{r}
t.test(banks$old_shortfall_loan_count, banks$new_shortfall_loan_count, paired = TRUE)
```

```{r}
banks %>%
  mutate(delta = old_shortfall_loan_count - new_shortfall_loan_count,
         `Generated Graph` = `Generated Graph`/1.4) %>%
  #count(delta) %>%
  ggplot() +
    geom_histogram(aes(x = delta), bins = 50, fill = "lightskyblue1") +
    geom_point(aes(x = delta, y = `Generated Graph`), alpha = 0.5, size = 1) +
    theme_linedraw() +
    theme(#axis.text.y = element_blank(), 
          #axis.ticks = element_blank(),
          #panel.grid.major = element_blank(),
          panel.grid.minor = element_blank()) +
    ggtitle("Change in Loans Fully Repaid") +
    xlab("Net Difference") +
    ylab("")
```

```{r}
loans <- banks %>%
  rename(old = old_shortfall_loan_count, new = new_shortfall_loan_count) %>%
  select(`Generated Graph`, `old`, `new`) %>%
  mutate(delta = old - new,
         y = -5)

banks %>%
  mutate(delta = old_shortfall_loan_count - new_shortfall_loan_count) %>%
  count(delta) %>%
  ggplot(aes(x = delta, y = n)) +
    geom_col(fill = "lightskyblue1", width = 1.25) +
    geom_point(data = loans, aes(x = delta, y = y), alpha = 0.2, size = 0.6) +
    theme_linedraw() +
    theme(#axis.text.y = element_blank(), 
          #axis.ticks = element_blank(),
          #panel.grid.major = element_blank(),
          panel.grid.minor = element_blank()) +
    ggtitle("") +
    xlab("Net Difference") +
    ylab("Count")
```

```{r}
points <- banks %>%
  rename(old = old_shortfall_dollars, new = new_shortfall_dollars) %>%
  select(`Generated Graph`, `old`, `new`) %>%
  mutate(delta = new - old,
         y = 0)

shortfall_diff <- banks %>%
  rename(old = old_shortfall_dollars, new = new_shortfall_dollars) %>%
  select(`Generated Graph`, `old`, `new`) %>%
  mutate(delta = new - old)
ggplot(data = shortfall_diff, aes(x = delta)) +
  #geom_histogram(alpha = 0.8, fill = "black", bins = 1000) +
  geom_density(alpha = 0.90, fill = "lightskyblue1") +
  geom_point(data = points, aes(x = delta, y = y), alpha = 0.3, size = 0.8) +
    scale_fill_brewer() +
    theme_linedraw() +
    theme(axis.text.y = element_blank(),
          axis.ticks = element_blank(),
          #panel.grid.major = element_blank()
          panel.grid.minor = element_blank()
          ) +
    ggtitle("Total Shortfall Difference") +
    coord_cartesian(ylim = c(0, 0.005)) +
    ylab("Density") +
    xlab("Dollar Change in Millions")
```

```{r}
degree_distribution %>%
  select(1,3) %>%
  mutate(Bank = rank(desc(in_degree), ties.method = "first"),
         in_degree = in_degree / 2) %>%
  rename(`In-Degree` = in_degree) %>% 
  ggplot(aes(x = Bank, y = `In-Degree`)) +
    geom_line(color = "skyblue1") +
    geom_point(color = "black") +
    theme_linedraw() +
    ggtitle("In-Degree Distribution") +
    ylab("Degree") +
    xlab("Bank (ranked in descending order)")
```

```{r}
degree_distribution %>%
  select(1,2) %>%
  mutate(Bank = rank(desc(out_degree), ties.method = "first"),
         out_degree = out_degree / 2) %>%
  rename(`Out-Degree` = out_degree) %>% 
  ggplot(aes(x = Bank, y = `Out-Degree`)) +
    geom_line(color = "skyblue1") +
    geom_point(color = "black") +
    theme_linedraw() +
    ggtitle("Out-Degree Distribution") +
    ylab("Degree") +
    xlab("Bank (ranked in descending order)")
```


```{r}
delta_banks <- banks %>%
  summarise(delinquent_loans = new_shortfall_loan_count - old_shortfall_loan_count,
            delinquent_banks = new_delinquent_count - old_delinquent_count,
            failed_banks = new_bank_fail_count - old_bank_fail_count,
            shortfall_banks = new_shortfall_bank_count - old_shortfall_bank_count,
            shortfall_dollars = new_shortfall_dollars - old_shortfall_dollars)
```

```{r}
#mean
delta_banks %>%
  summarise(mean_delinquent_loans = mean(delinquent_loans),
            mean_delinquent_banks = mean(delinquent_banks),
            mean_failed_banks = mean(failed_banks),
            mean_shortfall_banks = mean(shortfall_banks),
            mean_shortfall_dollars = mean(shortfall_dollars))

#median
delta_banks %>%
  summarise(median_delinquent_loans = median(delinquent_loans),
            median_delinquent_banks = median(delinquent_banks),
            median_failed_banks = median(failed_banks),
            median_shortfall_banks = median(shortfall_banks),
            median_shortfall_dollars = median(shortfall_dollars))

#SD
delta_banks %>%
  summarise(sd_delinquent_loans = sd(delinquent_loans),
            sd_delinquent_banks = sd(delinquent_banks),
            sd_failed_banks = sd(failed_banks),
            sd_shortfall_banks = sd(shortfall_banks),
            sd_shortfall_dollars = sd(shortfall_dollars))

#min
delta_banks %>%
  summarise(min_delinquent_loans = min(delinquent_loans),
            min_delinquent_banks = min(delinquent_banks),
            min_failed_banks = min(failed_banks),
            min_shortfall_banks = min(shortfall_banks),
            min_shortfall_dollars = min(shortfall_dollars))

#max
delta_banks %>%
  summarise(max_delinquent_loans = max(delinquent_loans),
            max_delinquent_banks = max(delinquent_banks),
            max_failed_banks = max(failed_banks),
            max_shortfall_banks = max(shortfall_banks),
            max_shortfall_dollars = max(shortfall_dollars))
```

